### ISSUE TITLE
Arguments to `_rbBabelBind` are hanging

### ISSUE THREAD

**Issue by zgotsch** [flexport/reflective-bind#19]
I tried to run `lodash-babel-loader` after `reflective-bind/babel` and it broke because the new variable introduced as an argument to `_rbBabelBind` was not transformed by `lodash-babel-loader`.

**Comment by dounan** [comment]
An update: we haven't been able to reproduce the issue internally since we ran into it. We will keep investigating. If anyone else runs into this, please let us know your reflective-bind version, babel version, babelrc setup, and the lodash-babel-loader version.
