### ISSUE TITLE
Optimize references to stateless functional component props

### ISSUE THREAD

**Issue by dounan** [flexport/reflective-bind#2]
Currently, references to the `props` argument of stateless functional components will be hoisted, but the way it is hoisted will still cause wasteful re-rendering.

The following code:

```js
function MyComponent(props) {
  return <PureChild onClick={() => alert(props.user.name)} />;
}
```

Will be transformed to:

```js
function _bbHoisted(props) {
  alert(props.user.name);
}

function MyComponent(props) {
  return <PureChild onClick={reflectiveBind(_bbHoisted, this, props)} />;
}
```

However, since props is a different object reference each time, this hoisting does result in any optimizations.

Instead, we should special case the `props` argument and look one level deep:

```js
function _bbHoisted(_temp) {
  alert(_temp.name);
}

function MyComponent(props) {
  return <PureChild onClick={reflectiveBind(_bbHoisted, this, props.user)} />;
}
```

In this example, `PureChild` will only re-render if the actual user object has changed.

Note that we should not hoist more than one level deep (i.e. `reflectiveBind(_bbHoisted, this, props.user.name`) because that could potentially change the behavior of the code: `props.user.name` could have been mutated and is not guaranteed to have the same value when the callback is called. Hoisting one level deep is more safe because developers know better than to mutate `props` which is controlled by React.

To determine if we are in a stateless functional component, we can use some heuristics:
- function returns JSX (or `React.createElement`)
- function has only one argument named `props`

**Comment by GollyJer** [comment]
Just read the Medium post and came to see if this worked with functional components.  
subscribed. :-D

**Comment by dounan** [comment]
@GollyJer the current transform does support functional components 😄  To use them without wasteful re-renders, simply avoid referencing `props` from within your inline function.

So instead of doing this:

```jsx
function MyComponent(props) {
  return <PureChild onClick={() => alert(props.user.name)} />;
}
```

Just do this:

```jsx
function MyComponent(props) {
  const name = props.user.name;
  return <PureChild onClick={() => alert(name)} />;
}
```

In general, avoiding accessing object attributes inside your inline function will get you better optimizations with `reflective-bind`.

**Comment by GollyJer** [comment]
@dounan Thanks for the follow-up!
Sorry for simple questions... but here goes.

I'm using ass much ES6 in my component I can. 
Like this.
```
const MyComponent = ({ user }) => (
  <PureChild onClick={() => alert(user.name)} />
)
```
But if I'm hearing you correctly then accessing the `.name` attribute via `user` won't be optimized?

I would need to do this?
```
const MyComponent = ({ user }) => {
  const { name } = user;
  return <PureChild onClick={() => alert(name)} />;
};
```

**Comment by dounan** [comment]
No problem. I'm happy to answer any questions 👍 

In this code:

```
const MyComponent = ({ user }) => (
  <PureChild onClick={() => alert(user.name)} />
)
```

PureChild will be re-rendered whenever the `user` object reference changes.

In the second example you gave:

```
const MyComponent = ({ user }) => {
  const { name } = user;
  return <PureChild onClick={() => alert(name)} />;
};
```

PureChild will only be re-rendered if the value of `name` changes.

**Comment by GollyJer** [comment]
Excellent.  Thanks for the explanation!
... and the package. 😃
