### ISSUE TITLE
Using 'extends <Reflective-bind-class>' syntax

### ISSUE THREAD

**Issue by ruimcf** [flexport/reflective-bind#24]
Would it be possible to create an implementation that exports a class which implements the `shouldComponentUpdate()` function from reflective-bind?

I imagine it would be something like this
``` javascript
\\ reflective-bind
import { shouldComponentUpdate } from 'reflective-bind';

export class ReflectiveBindComponent extends React.Component {
    constructor(extendedComponent) {
        this.extendedComponent = props.extendedComponent;
    }
 
    shouldComponentUpdate(nextProps, nextState) {
        return shouldComponentUpdate(this.extendedComponent, nextProps, nextState);
    }
}
```

``` javascript
import { ReflectiveBindComponent } from 'reflective-bind';

class MyComponent extends ReflectiveBindComponent {
    constructor(){
        super(this)
    }
}
```
Possible advantages:
- less verbose syntax
- it is more explicit than overriding React.Component.prototype.shouldComponentUpdate 

Possible problems with this idea:
- It is less clear about what it is doing. People could override the `shouldComponentUpdate` function in their component and not notice it. It is less explicit that ReflectiveBind implements shouldComponentUpdate function.
- I am not sure if there are some problems in order to pass additional props to the React.Component.
- It would also would need a implementation for React.PureComponent

I don't know if this is a useful use case, but I would just like to leave this suggestion. Thanks!

**Comment by dounan** [comment]
Thanks for the suggestion ruimcf! This syntax will definitely make it easier to use. Internally we actually have our own subclass of React.Component that gives us similar functionality and it works very nicely for us. Having said that, I am a bit hesitant to include this class in this library for a few reasons:
- Code bloat
- One more thing to maintain (and keep updated with React)
- Might need to also add Flow/Typescript types
- Pretty easy for a developer to write on their own.

We'll definitely keep it in mind though and if this becomes a popular request we will consider adding it in 😄
