### ISSUE TITLE
Alternative way to monkeypatch to silence warning?

### ISSUE THREAD

**Issue by beaugunderson** [flexport/reflective-bind#29]
When we use the monkeypatch given in the documentation I see this all over our console logs:

```
Warning: NoteLineComponent has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.
```

Is there an alternate way to achieve the monkeypatch that does not cause this warning?

**Comment by dounan** [comment]
Another option is to subclass `React.Component` with your own component class that overrides the `shouldComponentUpdate` and extend that component when you want a pure component.

```
import * as React from "react";
import {shouldComponentUpdate} from "reflective-bind";

export default class CustomPureComponent extends React.Component {
  shouldComponentUpdate(nextProps, nextState) {
    return shouldComponentUpdate(this, nextProps, nextState);
  }
}
```

**Comment by beaugunderson** [comment]
thanks @dounan! we'll try this soon :)

**Comment by beaugunderson** [comment]
this works great @dounan; thanks again!
