### ISSUE TITLE
Eslint plugin to detect potential stale render bugs

### ISSUE THREAD

**Issue by dmnd** [flexport/reflective-bind#9]
When app code uses an impure render callback function it's possible that reflective-bind's hoisting will cause a stale render bug. This should be statically detectable so it's be nice to have an eslint rule to point out such functions.

TODO: add example of app code that can cause a stale render

**Comment by dounan** [comment]
There is an example in https://github.com/flexport/reflective-bind/issues/3 that illustrates one possible case. I've closed that one in favor of this issue.

**Comment by dounan** [comment]
The library no longer aims to prevent stale render bugs due to transforming impure render callbacks. Instead, it is recommended to configure the babel transform so that render props are not transformed.
